// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/docs-config': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs-config.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs-config.post').default>>>>
    }
    '/api/docs/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs/[id].get').default>>>>
    }
    '/api/docs': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs/index.post').default>>>>
    }
    '/api/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}